stages:
  - test
  - deploy
image: python:3.8
test-job:
  stage: test
  script:
    - echo "Running tests ..."
    - python -m unittest discover -s hello-devops -p "devops"

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application ..."
